version: '3.8'

services:
  node:
    image: vaibhavrajnathchauhan/expense-sharing:5
    container_name: expense-sharing
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - redis
    
  redis:
    image: redis
    ports:
      - 6379:6379
  